# Generated by Django 2.2.4 on 2019-10-20 11:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
