# Generated by Django 2.2.4 on 2019-11-04 20:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mec', '0002_address_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('district_type', models.CharField(max_length=2)),
                ('boundaries', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
