# Generated by Django 2.2.4 on 2019-11-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mec', '0004_auto_20191106_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='districts',
            field=models.ManyToManyField(to='mec.District'),
        ),
    ]
